- name: Launch Worker Nodes
  hosts: worker_private
  become: true

  tasks:
    - name: Read master IP from hosts.ini
      shell: "awk '/^\\[master_public\\]/{getline; print}' hosts.ini | cut -d ' ' -f 1"
      register: master_ip_result

    - set_fact:
        master_ip_public: "{{ master_ip_result.stdout.strip() }}"

    - name: Read K3s token from file
      slurp:
        path: "{{ playbook_dir }}/k3s_token.txt"
      register: k3s_token_file

    - set_fact:
        k3s_token: "{{ k3s_token_file.content | b64decode }}"

    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          
    - name: Start k3s worker node
      shell: curl -sfL https://get.k3s.io | sh -s - agent --server https://{{ master_ip_public }}:6443 --token {{ k3s_token }} --kubelet-arg=cloud-provider=external
      args:
        creates: "/etc/systemd/system/k3s.service"


